#!/bin/sh

cd ${0%/*} || exit 1 # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication setWaveParameters

runApplication blockMesh

runApplication changeDictionary -dict system/changeDictionaryDict.1

#runApplication surfaceTransformPoints -scale '(1.035647 1.0356470 1.035647)' constant/triSurface/FB_symmetry_1set.stl constant/triSurface/FB_symmetry_1set1.stl

#rm -r log.surfaceTransformPoints

runApplication surfaceTransformPoints -translate '(3.5 0 -0.9)' constant/triSurface/model1_module_1set.stl constant/triSurface/model1_module_1set2.stl

runApplication surfaceFeatures

for i in 1 2 3  
do
    runApplication -s $i \
        topoSet -dict system/topoSetDict.${i}

    runApplication -s $i \
        refineMesh -dict system/refineMeshDict.${i} -overwrite
done

runApplication decomposePar

runParallel snappyHexMesh -overwrite

runApplication reconstructParMesh -constant

runApplication renumberMesh -constant -overwrite
 
runApplication checkMesh 

#runApplication setWaves

#runApplication decomposePar

#runParallel $(getApplication)

#runApplication reconstructPar

#------------------------------------------------------------------------------
