#!/bin/sh

cd ${0%/*} || exit 1 # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#runApplication blockMesh

#runApplication surfaceFeatures

#runApplication changeDictionary -dict system/changeDictionaryDict.1

#runApplication decomposePar

#runParallel snappyHexMesh -overwrite

#runApplication reconstructParMesh -constant

#renumberMesh -constant -overwrite
 
#runApplication checkMesh 

runApplication setWaveField

# Make the wave gauges
if [ -d "waveGaugesNProbes" ]
then
    rm -rf waveGaugesNProbes
fi
runApplication waveGaugesNProbes

# Correct the file waveGaugesNProbes/surfaceElevation_controlDict to yield
# the desired outputting frequency.
sed -i -e 's/face/lineFace/' waveGaugesNProbes/surfaceElevation_sets

rm -f log.changeDictionary
runApplication changeDictionary -dict system/changeDictionaryDict.1

runApplication decomposePar -latestTime

rm -f log.changeDictionary
runApplication changeDictionary -dict system/changeDictionaryDict.2

runParallel interWaveFoam 

runApplication reconstructPar


#------------------------------------------------------------------------------
